services:
  postgres:
    container_name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spring-starter

  app:
    build:
      ./
    container_name: 'spring'
    ports:
      - 8080:8080