db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

config:
  mail:
    sender: Berserk@gmail.com  # как лучше это использовать ?

spring.profiles.active: qa

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 613260792617-e94nfvithujgugnhnq73jfn0hs8csmk1.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope: openid, email, profile
          github:
            clientId: 8df1428b005d0d11d2c9
            clientSecret: 3f22f84ecda4b2d008dd45a81ffb8f572280e557
            redirectUri: http://localhost:8080/login/oauth2/code/github
            scope: openid, email, profile

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-starter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
#    hibernate:
#      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0b11t061@gmail.com
#    password: DO NOT DO THIS
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  version: @springdoc.version@
  swagger-ui:
    oauth:
      client-id: 8df1428b005d0d11d2c9
      client-secret: 3f22f84ecda4b2d008dd45a81ffb8f572280e557
      scopes: openid,email,profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  group-configs:
    - group: Rest API
      packages-to-scan: com.ob11to.spring
