db:
  username: ${username.value:postgres}
  password: pass
  driver: PostgresDriver
  url: postgres:5432
  hosts: localhost,127.0.0.1
  properties:
    first: 123
    second: 456
    third.value: Third
  pool:
    size: 12
    timeout: 10
  pools:
    - size: 1
      timeout: 1
    - size: 2
      timeout: 2
    - size: 3
      timeout: 3

config:
  mail:
    sender: Berserk@gmail.com  # как лучше это использовать ?

spring.profiles.active: qa

logging:
  level:
    root: INFO
    org.springframework.jdbc.core: TRACE

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-starter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      batch_size: 50
      fetch_size: 50
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
#    hibernate:
#      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: 0b11t061@gmail.com
#    password: DO NOT DO THIS
    properties:
      mail:
        transport:
          protocol: smtp
        debug: true
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  version: @springdoc.version@
  swagger-ui:
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  group-configs:
    - group: email
      paths-to-match: /email/**


